
server:
    error:
        # Função para esconder o stacktrace para o front
        # por padrão é always
        # on_param é usado para receber o trace caso seja adicionado ?trace=true no endpoint
        include-stacktrace: on-param

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
        username: root
        password: root

    jpa:
        # Atualização do JPA para que o banco seja atualizado sempre que iniciado
        hibernate:
            ddl-auto: update
        # Pede que a consulta seja apresentada em log        
        # show-sql: true

# Para apresentar em tela a consulta enviada ao banco de dados
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                # Mostra os valores imputados no banco
                # type: trace
