
server:
    error:
        # Função para esconder o stacktrace para o front
        # por padrão é always
        # on_param é usado para receber o trace caso seja adicionado ?trace=true no endpoint
        include-stacktrace: never

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
        username: root
        password: root

    jpa:
        # Atualização do JPA para que o banco seja atualizado sempre que iniciado
        hibernate:
            ddl-auto: update
        # Pede que a consulta seja apresentada em log        
        show-sql: true