
server:
    error:
        # Função para esconder o stacktrace para o front
        # por padrão é always
        # on_param é usado para receber o trace caso seja adicionado ?trace=true no endpoint
        include-stacktrace: never

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: root
        password: root

    # Atualização do JPA para que o banco seja atualizado sempre que iniciado
    jpa:
        hibernate:
            ddl-auto: update